group_project/core/urls.py
from django.urls import path

from .views import AddDiscountView, CheckoutView, OrderSummaryView, PaymentView, HomeView, ItemDetailView, \
    RequestRefundView, add_to_cart, alcohol_categories_list, remove_from_cart, remove_single_item_from_cart, signup, \
    logout_user

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout', CheckoutView.as_view(), name='checkout-page'),
    path('<int:pk>-<str:slug>/', ItemDetailView.as_view(), name='item-details'),
    path('alcohols', alcohol_categories_list),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<int:pk>-<slug>/', add_to_cart, name='add-to-cart'),
    path('add-discount/', AddDiscountView.as_view(), name='add-discount'),
    path('remove-from-cart/<int:pk>-<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<int:pk>-<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path(r'accounts/signup', signup, name='account-signup'),
    path(r'accounts/logout/', logout_user, name='logout'),
]

group_project/group_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

group_project/templates/alcohol_tree.html
{% load mptt_tags %}
<ul>
    {% recursetree alcohols %}
        <li>
            {{ node.name }}
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

group_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Alcohol Emporium</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>
{% include "navigation_bar.html" %}

<body>

<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

{% include "footer.html" %}
{% include "scripts.html" %}

</body>

</html>

group_project/templates/checkout-page.html
{% extends "base.html" %}

{% block content %}

    <main>
        <div class="container wow fadeIn">
            <h2 class="my-5 h2 text-center">Checkout form</h2>
            <div class="row">
                <div class="col-md-8 mb-4">
                    <div class="card">
                        <form method="POST" class="card-body">
                            {% csrf_token %}

                            <h3>Shipping address</h3>

                            <div class='hideable_shipping_form'>

                                <div class="md-form mb-5">
                                    <input type='text' placeholder='1234 Main St' id='shipping_address'
                                           name='shipping_address' class='form-control'/>
                                    <label for="shipping_address" class="">Address</label>
                                </div>

                                <div class="row">
                                    <div class="col-lg-4 col-md-12 mb-4">
                                        <label for="country">Country</label>
                                        {{ form.shipping_country }}
                                        <div class="invalid-feedback">
                                            Please select a valid country.
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-6 mb-4">
                                        <label for="shipping_zip">Zip</label>
                                        <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip'
                                               class='form-control'/>
                                        <div class="invalid-feedback">
                                            Zip code required.
                                        </div>
                                    </div>
                                </div>

                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" name="same_billing_address"
                                           id="same_billing_address">
                                    <label class="custom-control-label" for="same_billing_address">Billing address is
                                        the same as my shipping address</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                                           id="set_default_shipping">
                                    <label class="custom-control-label" for="set_default_shipping">Save as default
                                        shipping address</label>
                                </div>

                            </div>

                            {% if default_shipping_address %}
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" name="use_default_shipping"
                                           id="use_default_shipping">
                                    <label class="custom-control-label" for="use_default_shipping">Use default shipping
                                        address: {{ default_shipping_address.address|truncatechars:10 }}</label>
                                </div>
                            {% endif %}

                            <hr>

                            <h3>Billing address</h3>

                            <div class='hideable_billing_form'>
                                <div class="md-form mb-5">
                                    <input type='text' placeholder='1234 Main St' id='billing_address'
                                           name='billing_address' class='form-control'/>
                                    <label for="billing_address" class="">Address</label>
                                </div>

                                <div class="row">
                                    <div class="col-lg-4 col-md-12 mb-4">
                                        <label for="country">Country</label>
                                        {{ form.billing_country }}
                                        <div class="invalid-feedback">
                                            Please select a valid country.
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-md-6 mb-4">
                                        <label for="billing_zip">Zip</label>
                                        <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip'
                                               class='form-control'/>
                                        <div class="invalid-feedback">
                                            Zip code required.
                                        </div>
                                    </div>

                                </div>

                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" name="set_default_billing"
                                           id="set_default_billing">
                                    <label class="custom-control-label" for="set_default_billing">Save as default
                                        billing address</label>
                                </div>

                            </div>

                            {% if default_billing_address %}
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" name="use_default_billing"
                                           id="use_default_billing">
                                    <label class="custom-control-label" for="use_default_billing">Use default billing
                                        address: {{ default_billing_address.address|truncatechars:10 }}</label>
                                </div>
                            {% endif %}
                            <hr>

                            <h3>Payment option</h3>

                            <div class="d-block my-3">
                                {% for value, name in form.fields.payment_option.choices %}
                                    <div class="custom-control custom-radio">
                                        <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                                               class="custom-control-input" required>
                                        <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                                    </div>
                                {% endfor %}
                            </div>

                            <hr class="mb-4">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

                        </form>

                    </div>

                </div>

                <div class="col-md-4 mb-4">
                    {% include "order_snippet.html" %}
                </div>

            </div>

        </div>
    </main>

{% endblock content %}

{% block extra_scripts %}
    <script>
        const hideable_shipping_form = £('.hideable_shipping_form');
        const hideable_billing_form = £('.hideable_billing_form');

        const use_default_shipping = document.querySelector("input[name=use_default_shipping]");
        const use_default_billing = document.querySelector("input[name=use_default_billing]");

        use_default_shipping.addEventListener('change', function () {
            if (this.checked) {
                hideable_shipping_form.hide();
            } else {
                hideable_shipping_form.show();
            }
        })

        use_default_billing.addEventListener('change', function () {
            if (this.checked) {
                hideable_billing_form.hide();
            } else {
                hideable_billing_form.show();
            }
        })

    </script>
{% endblock extra_scripts %}

group_project/templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2021 Copyright: Alcohol Emporium
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

group_project/templates/home-page.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="container">
            <!--Section: Products v.3-->
            <section class="text-center mb-4">

                <div class="row wow fadeIn">

                    {% for item in object_list %}
                        <div class="col-lg-3 col-md-6 mb-4">

                            <div class="card">

                                <div class="view overlay">
                                    <img src="{{ item.image.url }}" style="width:250px;height:400px;"
                                         class="card-img-top" alt="">

                                    <a href="{{ item.get_absolute_url }}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>

                                <div class="card-body text-center">
                                    <a href="" class="grey-text">
                                        <h5>{{ item.item_type }}</h5>
                                    </a>
                                    <h5>
                                        <strong>
                                            <a href="{{ item.get_absolute_url }}"
                                               class="dark-grey-text">{{ item.item_name }}</a>


                                        </strong>
                                    </h5>

                                    <h4 class="font-weight-bold blue-text">
                                        <span class="label label-info">{{ item.country_origin }}</span><br>
                                        <span class="label label-info">{{ item.item_size }}cl</span>


                                    </h4>
                                    <h4 class="font-weight-bold pink-text">
                                        <strong>
                                            {% if item.discount_price %}
                                                <span class="label label-info">Discounted!<br> Was £{{ item.price }}<br> NOW £{{ item.discount_price }}</span>
                                            {% else %}
                                                £{{ item.price }}
                                            {% endif %}
                                        </strong>
                                    </h4>

                                </div>

                            </div>

                        </div>
                    {% endfor %}
                </div>

            </section>
            <!--Section: Products v.3-->

            <!--Pagination-->

            {% if is_paginated %}
                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination pg-blue">

                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}

        </div>
    </main>

{% endblock content %}

group_project/templates/navigation_bar.html
{% load cart_count %}
<!-- nav bar stuff here -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- company name -->
        <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">Alcohol Emporium</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="/">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="/checkout">
                        Checkout</a>
                </li>
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                            <i class="fas fa-shopping-cart"></i>
                            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:logout' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Login </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:account-signup' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

group_project/templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                    <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.item_name }}</h6>
                    <small class="text-muted">{{ order_item.item.item_description }}</small>
                </div>
                <span class="text-muted">£{{ order_item.get_final_price|stringformat:".2f" }}</span>
            </li>
        {% endfor %}
        {% if order.discount_code %}
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>{{ order.discount_code.code }}</small>
                </div>
                <span class="text-success">-{{ order.discount_code.percentage }}%</span>
            </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (GBP)</span>
            <strong>£{{ order.get_total|stringformat:".2f"}}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
        <form class="card p-2" action="{% url 'core:add-discount' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
                {{ discountform.code }}
                <div class="input-group-append">
                    <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
    {% endif %}

</div>

group_project/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="container">

            <div class="table-responsive text-nowrap">
                <h2>Order Summary</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.item_name }}</td>
                            <td>{{ order_item.item.price }}</td>
                            <td>
                                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.id order_item.item.slug %}"><i
                                        class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add-to-cart' order_item.item.id order_item.item.slug %}"><i
                                        class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td>
                                {% if order_item.item.discount_price %}
                                    £{{ order_item.get_total_discount_item_price }}
                                    <span class="badge badge-primary">Saving £{{ order_item.get_amount_saved|stringformat:".2f" }}</span>
                                {% else %}
                                    £{{ order_item.get_total_item_price|stringformat:".2f" }}
                                {% endif %}
                                <a style='color: red;'
                                   href="{% url 'core:remove-from-cart' order_item.item.id order_item.item.slug %}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan='5'>Your cart is empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.discount_code %}
                        <tr>
                            <td colspan="4"><b>Discount code</b></td>
                            <td><b>-{{ object.discount_code.percentage }}%</b></td>
                        </tr>
                    {% endif %}
                    {% if object.get_total %}
                        <tr>
                            <td colspan="4"><b>Order Total</b></td>
                            <td><b>£{{ object.get_total|stringformat:".2f" }}</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-warning float-right ml-2' href='/checkout'>Proceed to checkout</a>
                                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>

            </div>

        </div>
    </main>

{% endblock content %}

group_project/templates/payment.html
{% extends "base.html" %}
{% block content %}
    <main>
        <div class="container wow fadeIn">
            <h2 class="my-5 h2 text-center">Checkout form</h2>
            <div class="row">
                <div class="col-md-8 mb-4">
                    <div class="card">
                        <form class="card-body" method="POST">
                            {% csrf_token %}
                            <h3>Payment option</h3>

                            <div class="md-form mb-5">
                                <label for='card_num'>Card Number</label>
                                <input type='text' placeholder='16-digit card number, no spaces' id='card_num'
                                                                     name='card_num' class='form-control'/>
                            </div>
                            <hr class="mb-4">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Pay</button>
                    </div>
                </div>
            </div>
    </main>
{% endblock content %}

group_project/templates/product-page.html
{% extends "base.html" %}
{% block content %}
    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">
                    <div class="text-center">
                        <img src="{{ item.image.url }}" class="img-fluid" alt="">
                    </div>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">
                    <!--Content-->
                    <div class="p-4">
                        <p class="lead font-weight-bold">{{ item.item_name }}</p>
                        Country of Origin: {{ item.country_origin }}<br>
                        Alcohol Type: {{ item.item_type }}<br>
                        {% if item.discount_price %}
                            <div class="mb-3">
                                <a href="">
                                    <span class="badge purple mr-1">Discounted</span>
                                </a>

                            </div>

                            <p class="lead">
              <span class="mr-1">
                <del>£{{ item.price }}</del>
              </span>
                                <span>£{{ item.discount_price }}</span>
                            </p>
                        {% else %}
                            <p class="lead">
                                <span>£{{ item.price }}</span>
                            </p>
                        {% endif %}
                        <p class="lead font-weight-bold">Description</p>

                        <p>{{ item.item_description }}</p>

                        <form class="d-flex justify-content-left">
                            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                                Add to cart
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </a>
                            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                                Remove from cart
                            </a>

                        </form>

                    </div>

                </div>

            </div>
        </div>
    </main>
    <!--Main layout-->
{% endblock content %}

group_project/templates/request_refund.html
{% extends "base.html" %}

group_project/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();

</script>